### ISSUE TITLE
Migrated template not in bootstrap renderer

### ISSUE THREAD

**Issue by erwinsg** [Open-Attestation/decentralized-renderer-react-template#11]
Hi Team,

Plan to migrate from v1.5 to v2.0.
We encountered template renderer is not in bootstrap design in Storybook
Any missing import/code we miss to include?

Legacy template v1.5 located at "tlds\sg\gov\seab\"

**Comment by simboonlong** [comment]
you might need to include the legacy bootstrap [styles / scripts](https://github.com/OpenCerts/legacy-templates/blob/master/src/components/Layout/Bootstrap.js) on your own in Storybook. Put them at `.storybook > preview-head.html` refer to https://storybook.js.org/docs/react/configure/story-rendering#adding-to-head

additional info on migration -> https://docs.opencerts.io/docs/migrations/v1_to_v2
