### ISSUE TITLE
Multiple views feature

### ISSUE THREAD

**Issue by erwinsg** [Open-Attestation/decentralized-renderer-react-template#12]
Hi Team,

Possible to configure multiple viewer in Storybook? If yes, is there any reference?
Example, in single template have "Statement of Results" and "Explanatory Notes".

**Comment by cavacado** [comment]
Hey,
what do you mean by single template have "Statement of Results" and "Explanatory Notes".?

are you just trying to render multiple data in a single template?

if so, you can always customise the template to your needs.

**Comment by erwinsg** [comment]
possible to configure storybook have multiple views as below?
![image](https://user-images.githubusercontent.com/43283667/143983892-81111491-37da-4dc1-963b-be8447e80d08.png)

**Comment by cavacado** [comment]
what do you intend to achieve if you configure storybook to display a tabbed view?

storybook is only meant for devs to visualise the template and how it looks, I dont see a need for a dev to want a tabbed view.

if you want this kind of behavior in your project, then you'll have to code it up, you can reference opencerts website on how we are currently doing tabbed views.
