### ISSUE TITLE
To have an HTML page to preview OpenCerts document (similar to V1.5)

### ISSUE THREAD

**Issue by mmysgp** [Open-Attestation/decentralized-renderer-react-template#13]
Hi Team, 

Previously there is a test html file in the legacy templates to preview the generated OpenCerts document before issuing it on blockchain.
[[legacy-templates](https://github.com/OpenCerts/legacy-templates)/[test](https://github.com/OpenCerts/legacy-templates/tree/master/test)/index.html](https://github.com/OpenCerts/legacy-templates/blob/master/test/index.html)

We think it’s a very good feature which can be easily used in our ERP system to create a preview function.
We noticed that the legacy index.html does not work for V2 samples.  It must be due to the change introduced by V2.0. 
![image](https://user-images.githubusercontent.com/36496605/163751495-46618e07-053e-4d6a-9e4b-4bf6dcf785bf.png)
 
May I know whether you can provide a similar html page calling OpenCerts V2 renderer to preview documents or provide the detailed implementation guide for it?

Thanks.

**Comment by simboonlong** [comment]
for reference, [duplicate](https://github.com/OpenCerts/demo-opencerts-renderer/issues/380)

**Comment by mmysgp** [comment]
Thanks.
