### ISSUE TITLE
Renderer margin

### ISSUE THREAD

**Issue by WillVill** [Open-Attestation/decentralized-renderer-react-template#7]
When rendering the certificate on opencert.io there is a margin set to the body (margin: 8px;). This is an issue as when you want to print the document the margin will be applied. If the rendered document is exactly of A4 size then the document will have a margin top, left, bottom but not right as the width is then greater than the A4 width.

Another thing, would be best to add the following to index.html
```<meta charset="utf-8">```

**Comment by Nebulis** [comment]
Hello,

1) I have no idea what margin you refer too (I don't see any in the current version of the repo). That aside, this repository is meant to help you bootstrap your renderer. Feel free to change the style to fit your needs
2) Indeed it's better to add the charset, will do it tomorrow. Thanks for the feedback :)

**Comment by Nebulis** [comment]
Added charset in 8cd6a17475dc41eaecf1aefc2399eb50b39175b3
